ALTER SESSION SET CURRENT_SCHEMA=APP_OWNER;

-- Dealerships across the country
CREATE TABLE dealership (
  dealership_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100) NOT NULL,
  city          VARCHAR2(80),
  region        VARCHAR2(80)
);

-- Employees mapped to DB usernames and a home dealership

CREATE TABLE employee (
  employee_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  db_username    VARCHAR2(30) NOT NULL UNIQUE, -- e.g. SALES_ANNA, MGR_BOB (must match DB user)
  full_name      VARCHAR2(120) NOT NULL,
  role_code      VARCHAR2(10)  NOT NULL CHECK (role_code IN ('SALES','MANAGER')),
  dealership_id  NUMBER NOT NULL REFERENCES dealership(dealership_id)
);

ALTER TABLE employee ADD (password VARCHAR2(255));
 
CREATE TABLE review(
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id      NUMBER NOT NULL REFERENCES employee(employee_id),
    salesperson_id  NUMBER NOT NULL REFERENCES employee(employee_id),
    review_date     DATE   DEFAULT SYSDATE NOT NULL,
    review_text     CLOB   NOT NULL 
);

GRANT SELECT, INSERT, UPDATE, DELETE ON review TO manager_role; -- managers manage reviews
GRANT SELECT ON review TO sales_role; 

-- Customers
CREATE TABLE customer (
  customer_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name    VARCHAR2(120) NOT NULL,
  phone        VARCHAR2(40),
  email        VARCHAR2(120)
);

-- Vehicle catalog (simplified)
CREATE TABLE vehicle (
  vehicle_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vin          VARCHAR2(32) UNIQUE,
  model        VARCHAR2(60) NOT NULL,  -- e.g. Golf, Tiguan
  trim_level   VARCHAR2(60),
  model_year   NUMBER(4),
  base_price   NUMBER(12,2)
);

-- Service catalog: extras, CASCO, warranty, servicing, etc.
CREATE TABLE service_item (
  service_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_type  VARCHAR2(24) NOT NULL
    CHECK (service_type IN ('EXTRA_OPTION','CASCO','EXTENDED_WARRANTY','SERVICING','OTHER')),
  name          VARCHAR2(120) NOT NULL,
  description   VARCHAR2(4000),
  list_price    NUMBER(12,2)
);


-- Orders (one per car deal; services added as line items)
CREATE TABLE sale_order (
  order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealership_id   NUMBER NOT NULL REFERENCES dealership(dealership_id),
  customer_id     NUMBER NOT NULL REFERENCES customer(customer_id),
  salesperson_id  NUMBER NOT NULL REFERENCES employee(employee_id),
  manager_id      NUMBER REFERENCES employee(employee_id), -- optional approver
  order_date      DATE DEFAULT SYSDATE,
  status          VARCHAR2(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN','APPROVED','INVOICED','CANCELLED')),
  total_amount    NUMBER(14,2),
  created_by      VARCHAR2(30) -- DB username for auditing (set by app)
);

-- Car and service sales aren't tied, we can sell a car without a service or a service without a car
CREATE TABLE car_sale_item (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL REFERENCES sale_order(order_id) ON DELETE CASCADE,
    vehicle_id NUMBER NOT NULL REFERENCES vehicle(vehicle_id),
    unit_price NUMBER(12,2) NOT NULL,
    UNIQUE (order_id, vehicle_id)
);


CREATE TABLE service_sale_item (
    item_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    NUMBER NOT NULL REFERENCES sale_order(order_id) ON DELETE CASCADE,
    service_id  NUMBER NOT NULL REFERENCES service_item(service_id),
    qty         NUMBER(6,2) DEFAULT 1 CHECK (qty > 0),
    unit_price  NUMBER(12,2) NOT NULL,
    line_total  NUMBER(14,2) GENERATED ALWAYS AS (qty * unit_price) VIRTUAL
);

-- Basic privileges at the object level (further restricted by RLS/VPD below)
GRANT SELECT ON dealership  TO sales_role, manager_role;
GRANT SELECT ON employee    TO manager_role;         -- managers can see team roster
GRANT SELECT ON customer    TO sales_role, manager_role;
GRANT SELECT ON vehicle     TO sales_role, manager_role;
GRANT SELECT ON service_item TO sales_role, manager_role;

GRANT SELECT, INSERT, UPDATE ON sale_order TO sales_role, manager_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON car_sale_item TO sales_role, manager_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON service_sale_item TO sales_role, manager_role;

-- Table to store raw AI input text for embedding generation
CREATE TABLE ai_raw_input (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealership_id NUMBER NOT NULL REFERENCES dealership(dealership_id),
  src_text      CLOB NOT NULL,
  is_embedded   CHAR(1) DEFAULT 'N' CHECK (is_embedded IN ('Y','N'))
);

GRANT SELECT, INSERT, UPDATE ON ai_raw_input TO app_role;

-- Table to store AI-generated document embeddings for similarity search from ai_raw_input
-- is populated from load_embeddings.py
CREATE TABLE ai_docs (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealership_id NUMBER NOT NULL,
  src_text     CLOB,
  embedding    VECTOR(512, FLOAT32) -- to be adjusted regarding the model used
);

DROP TABLE ai_docs;

GRANT SELECT, INSERT ON ai_docs TO sales_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ai_docs TO manager_role;